### ISSUE TITLE
[CHORE] Deprecate front-of-card actions

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/Migaku-Kanji-Addon#106]
Front of card actions should be removed, since it's presence and use-case is unproven. You can mark known/delete on the back of cards, and you shouldn't ever really be coming across excess kanji cards that you already know well. If you do, that's an issue with the method used in which the cards were created.

![image](https://user-images.githubusercontent.com/3240185/142777515-d9fddaae-308e-41c3-a20b-69d2724afa4e.png)

**Comment by RicBent** [comment]
I agree with this. Thought it was useful at first but in the end I actually never used it because I always double check the back of the cards before deleting them.

And for those users who want to do it as fast as possible #42 should be enough.

**Comment by saxoncameron** [comment]
Alright, this is very low impact, so might as well include it before anki web.
