### ISSUE TITLE
[FEATURE] Readings linked to cards; stats for reading frequency

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/Migaku-Kanji-Addon#108]
Discord user `ガリン#4920` suggests:
https://discord.com/channels/752293144917180496/846925957302714388/912586342368706611
> suggestion: make the readings of the kanji clickable and blue when you have a word with that certain reading in your collection
> this way we can click on a reading and see what other words share the same reading of that kanji
> and maybe some stats about which reading is the most common so all of the readings' percentages sum up to a 100%

Which is essentially 2 ideas, as I understand it:
1. Make individual readings within each section (kunyomi, onyomi, nanori) clickable to view cards in browser with that specific combo of kanji + reading; and,
2. Breakdown of reading frequency, e.g. showing a percentage suffix after each individual reading that sums to 100%.

#2 would have to be sourced from some definitive resource, rather than a user's collection, which wouldn't be complete.

For clarity, this is all in reference to this section:
<img width="966" alt="Pasted_Image_23_11_21__9_20_pm" src="https://user-images.githubusercontent.com/3240185/143007153-e941380c-ebcb-4449-bcbf-027d01f06d98.png">

**Comment by saxoncameron** [comment]
@RicBent any comments on feasibility or desirability for a feature such as this? In terms of whether we assign this to a potential milestone, or archive as a latent "someday, maybe".

**Comment by RicBent** [comment]
I think if we ever do 1 it shouldn't actually link to the cards you have with that reading but highlight the corresponding words in the vocab section. This could be implemented using the output of the Furigana distribution fairly easily.
Considering the readings section doesn't have any interactivity this would interfere with, there wouldn't be any downside adding this.
However I also don't see many people actually using it as seeing which reading is used in which words isn't too difficult by just looking at the vocab section itself.

As for 2 I really don't like the idea of adding more text to an area most people don't use anyways. Maybe we can order readings by frequency and also make uncommon ones slightly gray.
Considering this should work even if you don't have any linked vocab, a fair amount of scraping texts would have to be done to get accurate data for this.
Again, this doesn't seem like a feature that would be used by many, however probably by more than 1.

Certainly a `someday, maybe` candidate imo.

**Comment by saxoncameron** [comment]
Archiving for now, there are certainly more pressing/obvious features for the time being.

FYI for any onlookers - we store/archive issues such as these in the `someday, maybe` milestone, so they don't get lost just because it's not convenient to implement it now. We close the issue to reduce noise so as not to detract from other open issues. It won't live in `someday, maybe` forever - it'll either be added to a future milestone candidate, or closed. All in good time.
