### ISSUE TITLE
[BUG] "Create Kanji Cards From Selection" causes an error

### ISSUE THREAD

**Issue by fw42** [migaku-official/Migaku-Kanji-Addon#122]
I have a pre-existing sentence mining deck, which is using the Migaku note type. When selecting notes from that deck in the browser and clicking "Create Kanji Cards From Selection" (under "Edit"), I get the following error message:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-12-06 20:41:17
Add-ons possibly involved: ⁨Migaku Kanji GOD⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/flo/Library/Application Support/Anki2/addons21/1872210448/__init__.py", line 166, in <lambda>
    lambda: CreateCardsFromNotesDialog.show_modal(browser.selectedNotes(), browser)
  File "/Users/flo/Library/Application Support/Anki2/addons21/1872210448/create_cards_from_notes_dialog.py", line 123, in show_modal
    dlg = cls(note_ids, parent)
  File "/Users/flo/Library/Application Support/Anki2/addons21/1872210448/create_cards_from_notes_dialog.py", line 43, in __init__
    Qt.Checked if (field_name in last_checked and last_checked[field_name]) else Qt.Unchecked
TypeError: argument of type 'NoneType' is not iterable
```

This happens with different notes, different decks, different kanji, different note types, etc.

I'm probably doing something wrong myself but a more descriptive error message (rather than a crash report) would be useful.

Thanks and keep up the great work!

**Comment by saxoncameron** [comment]
@fw42 would you mind please also providing:
- What operating system and version you're on (Windows, Linux, Mac etc)
- What version of Anki you're using

**Comment by saxoncameron** [comment]
Please disregard my original comment, I see you have system and version in your error message. Thanks!

**Comment by fw42** [comment]
Looks like it's happening on Windows too: https://www.reddit.com/r/ImmerseWithMigaku/comments/ra5akd/error_while_trying_to_create_kanji_cards_from/

**Comment by RicBent** [comment]
Fixed with https://github.com/migaku-official/Migaku-Kanji-Addon/commit/4c5ccfdf956076a6b790dc9a1f33b7b6570746a6

**Comment by fw42** [comment]
Thank you!
