### ISSUE TITLE
[BUG] Editing Card Types triggering error with latest Beta v5 release

### ISSUE THREAD

**Issue by seandub89** [migaku-official/Migaku-Kanji-Addon#123]
With the latest Beta V5 release, clicking on the "Cards" in the browser (or any other method) triggers the below error. Requires disabling the addon to adjust any card styles/templates. 

> Debug info:
> Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
> Platform: Windows 10
> Flags: frz=True ao=True sv=1
> Add-ons, last update check: 2021-12-06 10:15:25
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt\webview.py", line 493, in handler
>   File "aqt\editor.py", line 483, in <lambda>
>   File "aqt\editor.py", line 366, in _onCardLayout
>   File "C:\Users\Sean\AppData\Roaming\Anki2\addons21\1872210448\card_layout.py", line 12, in CardLayout_init_hook
>     note_type = note.note_type()
> AttributeError: 'Note' object has no attribute 'note_type'

**Comment by saxoncameron** [comment]
Discord user `KontrastJZ#1482` reports the same issue and error message.
https://discord.com/channels/752293144917180496/846925957302714388/919006147816587334

Further context:
> [editing] Any note type gives me this error

And, later:
> so i disabled beta5 from the github and it's working just fine with the last one on ankiweb

Have asked @seandub89 to try on the version posted on AnkiWeb, since this error was aslo reported against beta v5.

**Comment by RicBent** [comment]
Fixed with https://github.com/migaku-official/Migaku-Kanji-Addon/commit/09e9bb29c7cfc634f2039ca6bd342383f8e6494e
