### ISSUE TITLE
[QUESTION] Support for Chinese characters - Migaku Hanzi?

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/Migaku-Kanji-Addon#124]
This has been requested/asked a handful of times now, so I'm opening an issue to centralise discussion and to defer people to in future.

**Getting right to the point - this is not on our roadmap right not.** However, it's certainly very possible and we think it would work very well for hanzi. It will likely require competent volunteers, some discussion, or a fork of this project.

The reason it's not on our roadmap currently (as of EOY 2021):
- [We already have many features planned](https://github.com/migaku-official/Migaku-Kanji-Addon/milestones) from `1.1.0` -> `1.3.0` and beyond, which will keep us busy for a long time.
- The primary contributors so far (@RicBent and I) are Japanese learners, which has been a big motivator for us.
- There's a not-insignificant matter of sourcing the right data, and licensing, etc.

Thinking aloud, for this to become a reality, we'd need to find the following:
- An alternative to KanjiVG.
  - [HanziVG looks promising, and might be the solution - I haven't looked into it though](https://github.com/Connum/hanzivg). 
- An alternative parser for readings (perhaps with whatever Migaku Chinese is using under the hood?).
- An alternative to [Draw Me a Kanji](https://mbilbille.github.io/dmak/) (since that uses KanjiVG under the hood and would therefore be limited to the range of characters used in Japanese).
  - Perhaps [Hanzi Writer](https://hanziwriter.org/docs.html)...?
- Suitable replacement source data for all the fields in [the current kanji database](https://docs.google.com/spreadsheets/d/1aw0ihw0RpmejWLTUynrFYjmOfLdzcPVrDX7UM50lwBY/edit#gid=2109245908) (like keyword, primitives, meanings, stories, etc. etc.)

Whether this would be a sister project forked from this one, or whether Migaku Kanji would be expanded in scope to decouple itself from Japanese specifically and support both Japanese/Chinese and potentially other languages, is unclear to me. There would certainly be a lot of shared UI, so perhaps a monorepo structure would be suitable. No matter how you slice it though, it would be a lot of work...! 😅

**Comment by saxoncameron** [comment]
Archiving for now.

**Comment by seandub89** [comment]
Regarding the database, Heisig has both "Remembering the Hanzi Simplified/Traditional" available, so that can be leveraged...Arguably. any character that's common between Chinese/Japanese wouldn't need different notes/keywords (at least as a starting point)

**Comment by saxoncameron** [comment]
One thing we'd like to do longer term is separate data from the addon entirely and have it importable. Because we want to be careful with licensing. [We have a task for that here](https://github.com/migaku-official/Migaku-Kanji-Addon/issues/112). Ideally, we'd have [our own open-source system for user-submissions](https://github.com/migaku-official/Migaku-Kanji-Addon/issues/113) of stories, so we wouldn't be relying on third-party data that may or may not be happy about us including their data in this addon.

But yes, ostensibly RTH data (if we could a nice way to parse it) could fill out some of those fields in the kanji db.

That original kanji db spreadsheet was compiled from many different sources iirc, and it was done a few years ago so I thik even those sources are a little lost to time and memory.

**Comment by alyssabedard** [comment]
I will work on a database similar to the Migaku Kanji database mentioned above. If anyone wants to help me with the data, send me a DM on the Migaku Discord server (@ aly888) ✌🏼

**Comment by mdm508** [comment]
I have been using Hanzi Writer for a while and have found it very easy and pleasant to use. its very well documented and super flexible. All the stroke data for Hanzi Writer comes from 'Make me a Hanzi'. https://github.com/skishore/makemeahanzi

Make me a Hanzi has stroke data on both simplified and traditional characters and is by far the most high quality stroke data I have been able to find.

**Comment by seandub89** [comment]
> I will work on a database similar to the Migaku Kanji database mentioned above. If anyone wants to help me with the data, send me a DM on the Migaku Discord server (@ aly888) ✌🏼

Found a couple starting points, should all be from publicly available sources, but 3000 is definitely not comprehensive.
Pleco is also massively helpful for Chinese but their dictionary is proprietary, not sure what the rules are. If we just use their DB as a starting point and change the data, is that permissible?

https://github.com/agj/3000-traditional-hanzi
[RSH_v2.txt](https://github.com/migaku-official/Migaku-Kanji-Addon/files/7832428/RSH_v2.txt)

**Comment by mdm508** [comment]
> > I will work on a database similar to the Migaku Kanji database mentioned above. If anyone wants to help me with the data, send me a DM on the Migaku Discord server (@ aly888) ✌🏼
> 
> Found a couple starting points, should all be from publicly available sources, but 3000 is definitely not comprehensive. Pleco is also massively helpful for Chinese but their dictionary is proprietary, not sure what the rules are. If we just use their DB as a starting point and change the data, is that permissible?
> 
> https://github.com/agj/3000-traditional-hanzi [RSH_v2.txt](https://github.com/migaku-official/Migaku-Kanji-Addon/files/7832428/RSH_v2.txt)

That first dataset looks great! It looks like he was using [cjkvi-ids](https://github.com/cjkvi/cjkvi-ids) for the character decompostiton, or something similar. that seems like it could be useful.

**Comment by alyssabedard** [comment]
I have compiled a list of frequency lists and other relevant information we could use here : 
https://alyssabedard.notion.site/alyssabedard/ae2f7e44652b4d12a3e2200d275ed06f

@seandub89   let me know if you want me to add you so you can edit and comment on the Notion page. I have added @mdm508 

In the Dropbox you will find RSH, HSK 2.0, HSK 3.0, General Standard Chinese Characters and Jun Da's Frequency lists (汉字)

**Comment by seandub89** [comment]
@alyssabedard  Sure, would be happy to contribute anything I can. Can't code but can provide feedback on features etc..
