### ISSUE TITLE
[BUG] Kanji Settings window could have better resizing behaviour

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/Migaku-Kanji-Addon#126]
Discord users `mikeycp#2487` and `JMigCarrier#3963` report dissatisfaction with the current resizing capabilities of the Kanji Settings window. Both of these users are on Windows 10.
https://discord.com/channels/752293144917180496/846925957302714388/917912983571689483
> is there a reason we're not able to resize the settings window? at least on my system it's way too tall

> I think I have the same issue, in my 1920x1080 screen, Kanji Settings are always missing the top or the bottom, which is very cumbersome because there are buttons one may want to use outside of the screen
> I end up dragging the window until eventually it switches whether the bottom or the top is missing to access what I want

![image](https://user-images.githubusercontent.com/3240185/145124295-cb04b5a7-3760-44bb-9693-d30e1c66a2dd.png)

I'm on OS X Catalina and can resize the window down to this:
![image](https://user-images.githubusercontent.com/3240185/145124472-d6ac9b00-d7a0-4201-b863-9252eef42ee6.png)

But incidentally it seems like without sufficient vertical space, everything gets squished to the point that it becomes unusable, instead of going into a vertical scroll like you'd expect.
![Pasted_Image_8_12_21__10_31_am](https://user-images.githubusercontent.com/3240185/145124497-6025a5a6-26c9-481b-bd2f-db09d83453dc.png)

**Comment by apommel** [comment]
I have the same issue of a too tall settings window on a laptop whereas it works fine on my desktop even though my laptop screen resolution is higher. It may have to do with UI scaling.

A better resizing behavior would be greatly appreciated, but also an appropriate initial size of the settings window when first opened.

**Comment by saxoncameron** [comment]
Discord user `Kirin#6090` reports an issue in the same neighbourhood:
https://discord.com/channels/752293144917180496/846925957302714388/918488923561402389
> So I'm trying to add a field on the kanji settings and the add button is at the bottom, but it won't let me move the window up high enough to click on the button. When I try to move it up it snaps back down automatically. Can anyone help? Thanks

**Comment by saxoncameron** [comment]
Seems like this issue is quite prevalent and affecting many users @RicBent  - we've had at least 4 separate users report problems with the sizing behaviour of the settings window.

Might be a good quality of life fix that mightn't be too much effort compared to some other issues.

**Comment by RicBent** [comment]
Fixed with https://github.com/migaku-official/Migaku-Kanji-Addon/commit/1f3c8dc38566312c7b561d1d769bb4a4ed5061af

Adds scrollbars whenever the window gets too small.
