### ISSUE TITLE
[BUG] Anki freezes up during reviews; possibly due to learn-ahead card creation

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/Migaku-Kanji-Addon#127]
Discord user `DiscoTiger#0230` reports:
https://discord.com/channels/752293144917180496/846925957302714388/918006206755405834
> It's hardly a good bug report, and more like a mere suspicion, but after using the addon for 2 days I've noticed a few times that during my reps Anki breaks in a strange way... I suddenly lose the ability to answer cards, suspend them, etc. The keyboard shortcuts don't work and if I click the buttons Anki doesn't respond. I can't use the shortcuts to flip cards either, though I can flip cards with the mouse. The only way to fix it seems to be restarting anki. Migaku addons shortcuts all seem to be working though. It could be coincidence, or due to another addon, but I've never had a similar problem before and the only thing I've changed about my setup is installing kanji god. So I'm wondering if anyone else experiences something like this. 
> (edit just happened again, going to try disabling other addons)
> (edit 2 it happened again with ONLY the kanji god addon and migaku japanese addons enabled) 

> My intuition was that something happens related to automatic kanji card creation, where during my reps I pass a threshold of cards, trigger the kanji god addon to scan my deck and pre generate some kanji cards, and during that process it freezes
> Also, I disabled the kanji addon and did a few hundred reps today with no issues
> The reason I think this is plausable is because people were reporting issues with automatic card creation in other places. I for one had anki crash when I tried to make a card with yomichan, but since disabling kanji god it's been fine. 

User `jonavano#8565` chimed in:
https://discord.com/channels/752293144917180496/918006206755405834/918473285279293482
> I have the exact same issue, for me it only breaks when reviewing new cards and so far only with cards created by migaku browser add-on( so not the kanji cards), also for me my only change was adding the kanji god add-on

**Comment by saxoncameron** [comment]
Seems like a cross-platform issue, as user `DiscoTiger#0230` reports being on windows 11, whereas user `jonavano#8565` reports manjaro linux; both using Anki 2.1.35.

**Comment by saxoncameron** [comment]
Relevant discussion from Discord:

Further investigation from `DiscoTiger#0230` in trying to nail this issue's source:
https://discord.com/channels/752293144917180496/918006206755405834/918777354183122995
> Today I reviewed with only Kanji God enabled
> The first time I started anki, I could not use shortcuts to progress reviews.
> I restarted Anki and reviews worked normally again.
> After a while my screen flashed, which makes me think I triggered some automatic process by the addon, and after that I lost my shortcuts again.
> Interestingly, unlike before where anki would freeze completely if I tried to progress reviews by clicking the "good" button, I could review normally with my mouse but not my keyboard.
> I also found that the ctrl-z shortcut still worked.
> The cards I'm reviewing are from the JLPT N3 Tango premade deck, and the bug occurred while reviewing an old card not learning a new one

User `jonavano#8565` responds in kind:
https://discord.com/channels/752293144917180496/918006206755405834/918795727008837652
> with the flashing i can see a card for a split second before it gets skipped and from then onward I can use the shortcuts anymore
> So far it only happened when reviewing new cards. which is different from discotiger, the rest is the same

**Comment by saxoncameron** [comment]
I've been able to replicate this exact issue on my Mac during my reviews.

I was reviewing a pre-made deck with learn-ahead enabled, and after reviewing a new card my keyboard shortcuts (pass/fail, spacebar) failed to work. I checked my card browser immediately, and could verify that there was a brand-new kanji card created that corresponded with a freshly-upcoming card in my pre-made deck. 

This not only confirms the issue as suspected, but also that the error is consistent across desktop platforms.

**Comment by saxoncameron** [comment]
Seems like this might not even be concentrated specifically to learn-ahead creation, but to card creation in general:

Today I was doing my reviews, and opened the lookup browser for a kanji, and created a Recognition card for it there. From that point, my keyboard shortcuts no longer worked.

**Comment by fw42** [comment]
I have the same problem (Anki 2.1.35 on Mac OS X 12.0.1).

**Comment by saxoncameron** [comment]
Thanks for chiming in @fw42 - this one I think is pretty well nailed down, it's just a matter of time. 👌

**Comment by saxoncameron** [comment]
I think this one is no longer occurring...? Closing for now
