### ISSUE TITLE
[FEATURE] Settings synchronization between different computers

### ISSUE THREAD

**Issue by apommel** [migaku-official/Migaku-Kanji-Addon#128]
I sometimes use Anki on different computers (laptop and desktop) with the same profile. It would be nice if the Kanji GOD settings where synchronized through Ankiweb in order to not have to set up on each machine.

**Comment by saxoncameron** [comment]
Hi @apommel! We already have an issue for this: #51 - which we've marked and archived as `someday, maybe`.

If you feel strongly about it, please voice your support on that issue by either giving it a thumbs-up, or discussing it if you have something to say about it. Thanks!

**Comment by apommel** [comment]
Thanks for the feedback! You may want to reopen the older issue even if it is not a priority for now so that we may find it in the issues list and know that it is somehow considered.

**Comment by saxoncameron** [comment]
Yes that is fair, although keeping those closed is actually a conscious decision of ours, as specified in the README under the `Roadmap` title:
> Note that we have a dedicated `someday, maybe` milestone where we archive long-term or uncertain plans. We keep these issues closed so long as we have no immediate plans to work on them in the foreseeable roadmap. However, if you feel strongly about a feature we encourage you to comment on the issue or give it a thumbs-up.
