### ISSUE TITLE
[FEATURE] Add a settings option for stroke diagram draw speed

### ISSUE THREAD

**Issue by ItsMePairoa** [migaku-official/Migaku-Kanji-Addon#129]
When we set the kanji to auto draw, you (we) should be able the trace/shadow of how the kanji will be finished, that way you don't have to wait for the kanji the finish but also can see how exactly it looks. 
Also, I don't know there's already a feature for this or not but we should be able to adjust the kanji drawing stroke's speed too.
(someone on discord suggested me to post the idea here, don't know if this is the right place or not though...)

**Comment by saxoncameron** [comment]
A trace/shadow isn't necessary because you can already set your diagram to start fully drawn:
![image](https://user-images.githubusercontent.com/3240185/146301968-6a295abe-1b7c-4dcb-b052-54252098185a.png)
![image](https://user-images.githubusercontent.com/3240185/146301974-e7f122ef-88b1-4195-945f-c97a383fb11c.png)

**Comment by saxoncameron** [comment]
We currently don't have the draw speed as an option since we are already very option-heavy

**Comment by saxoncameron** [comment]
@ItsMePairoa I have updated this issue to have it correspond to your feature request for stroke diagram speed.

It is not on our roadmap currently. However, users who'd like this feature can upvote/thumbs-up and discuss it here. For now, I will archive this under the `someday, maybe` milestone; this is where we park issues/requests that aren't in our immediate roadmap and _perhaps_ might make it in, one day.

If you had something else in mind for your trace/shadow request, consider opening a separate issue for a feature request, so we have just one thing/request per issue. Thanks!
