### ISSUE TITLE
[CHORE] Add kanji database source files and generating scripts to repo

### ISSUE THREAD

**Issue by RicBent** [migaku-official/Migaku-Kanji-Addon#13]
Currently the repo just contains the pre-built kanji database.

The repo should instead include all source files and scripts necessary to generate that file.

**Comment by saxoncameron** [comment]
@RicBent is this `someday, maybe`, or?

**Comment by RicBent** [comment]
Yeah, it is. Low priority because the scripts to generate the original database are pretty much useless because the database is now only generated from itself and the google sheet.
