### ISSUE TITLE
[BUG] Error when adding new cards

### ISSUE THREAD

**Issue by objestik** [migaku-official/Migaku-Kanji-Addon#131]
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-12-18 19:21:42

Caught exception:
Traceback (most recent call last):
File “aqt\taskman.py”, line 101, in on_closures_pending
File “aqt\taskman.py”, line 71, in
File “aqt\taskman.py”, line 90, in wrapped_done
File "aqt\operations_init.py", line 117, in wrapped_done
File “aqt\operations_init_.py”, line 133, in _fire_change_hooks_after_op_performed
AttributeError: ‘NoneType’ object has no attribute ‘changes’

**Comment by saxoncameron** [comment]
Hi @objestik - thanks for reporting this bug.

Could you please provide us with additional information, as per the bug issue template?
<img width="495" alt="image" src="https://user-images.githubusercontent.com/3240185/146709638-1ee1ef76-82fb-4e1e-bb47-314ff483d19c.png">

Particularly, we'll need to know:
- How you encountered this bug (there are a few ways to create new cards!)
- Whether you consistently encounter this bug, and if so the steps to replicate it
- What platform and versions you're on

**Comment by objestik** [comment]
> Hi @objestik - thanks for reporting this bug.
> 
> Could you please provide us with additional information, as per the bug issue template?
> 
> Particularly, we'll need to know:
> 
> * How you encountered this bug (there are a few ways to create new cards!)
> * Whether you consistently encounter this bug, and if so the steps to replicate it
> * What platform and versions you're on

I have this bug using Migaku Kanji - 1.0.0-beta.5.

**Steps to reproduce the error:**
1. From Anki's home screen, click "Add" to add a new card. 
2. Fill out the card fields. 
3. Click the "Add" button to add the card to your deck.
4. The error will appear (as shown below).

**Expected behavior**
An error should not appear when I click the "Add" button when creating a card. 

**Additional context** 
However, cards are being added without issue despite the error. It's the error that pops up every time I click on the add button. 

**Whether you consistently encounter this bug.**

It appears every time I try to add a new card.
When I turn off the Migaki Kanji add-on, it no longer appears. 

**OS:** Windows 11.
**Anki version:**  2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2.


Screenshot: 
![image](https://user-images.githubusercontent.com/28157614/146760810-c80456d5-bff4-40de-8605-be05d302ec5e.png)

**Additional add-ons that I have installed:**
![image](https://user-images.githubusercontent.com/28157614/146763769-a5db83b3-9dc1-4f6a-b1bb-c2ab949bef0b.png)

**Comment by saxoncameron** [comment]
Awesome, thanks for the detail. It's a busy time at the moment, but we will get around to looking at this. 👍

**Comment by ianki** [comment]
+1, after updating to Anki 2.1.49. I started getting this error and narrowed it down to Migaku Kanji God.

This error also unfortunately seems to also make Migaku Japanese have some problems with connection to the browser extension and I can no longer add dictionary definitions when this happens.

**Comment by MysthicG** [comment]
+1 also had this issue in Anki 2.1.49, same error message (exactly the same)

**Comment by RicBent** [comment]
Fixed with https://github.com/migaku-official/Migaku-Kanji-Addon/commit/242b7dfb0191e94cc7cb993babf08a3707ed158d

**Comment by objestik** [comment]
This issue has been resolved for me. It works as intended.
