### ISSUE TITLE
[BUG] Learn ahead kanji are added for suspended cards

### ISSUE THREAD

**Issue by ianki** [migaku-official/Migaku-Kanji-Addon#147]
**Describe the bug**
When using the learn ahead kanji feature, I got kanji cards created for sentence cards that are suspended.

**To Reproduce**
1. Set up a deck for learn-ahead cards
2. Exit settings
3. Cards get created regardless of cards being suspended or not

**Expected behavior**
My expectation is that suspended cards are ignored.

**Desktop (please complete the following information):**
 - OS and Version: Windows 10
 - Anki Version 2.1.49

**Comment by RicBent** [comment]
Thanks for the report! I will look into this.

**Comment by RicBent** [comment]
Should be easily fixable by altering the query here: https://github.com/migaku-official/Migaku-Kanji-Addon/blob/49f7d0b9b70a57535a115fb11259a8c5ece021c5/addon/kanji.py#L435

Should be able to do this tomorrow.

**Comment by ianki** [comment]
Yeah, locally I added the "AND queue>=0" condition.
