### ISSUE TITLE
[BUG] Clicking "study" on a deck causes an error

### ISSUE THREAD

**Issue by NeverDenied** [migaku-official/Migaku-Kanji-Addon#150]
**Describe the bug**
clicking study on a deck pops up two errors from what looks like kanji god.

**To Reproduce**
have Kanji god and migaku anki addons updated to beta 9 and alpha 12
open deck
click study

**Desktop (please complete the following information):**
 - OS and Version: Windows 10
 - Anki Version 2.1.49]

**Additional context**
latest versions of addons
kanji god beta 9
migaku anki alpha 12
all addons other than the two migaku disabled same error
error doesn't show on alpha 11

**Screenshots**
![anki_RiIfwloHJS](https://user-images.githubusercontent.com/2957755/148658983-8e2d28c4-5318-4f15-8705-a1aea4648a58.png)
![anki_YrDXXYYgsV](https://user-images.githubusercontent.com/2957755/148658985-470a9e85-3fc7-4512-a565-76c2250db4af.png)

**Comment by saxoncameron** [comment]
Additional context from @NeverDenied in Discord:
> downgraded to an earlier version and doesnt do it, tried going back to the latest version that was giving my the problem and doesn't seem to show anymore
> tried disabling all the addons while i was having the issue but it kept showing up.

Seems to no longer be an issue.
