### ISSUE TITLE
[BUG] New Kanji Cards not being added after making a Sentence Card.

### ISSUE THREAD

**Issue by evka745** [migaku-official/Migaku-Kanji-Addon#155]
Automatic Kanji cards don't get made or even checked after I add a new sentence card with the card exporter. 

Anki Version 2.1.35 
Kanji GOD Add-On Ver. 1.0.0-beta.11 (Ankiweb ver.)
macOS Monterey 12.1 M1 Macbook Pro

![image](https://user-images.githubusercontent.com/82726788/148880639-c78eb3a1-da6e-41d8-840b-8a6f7f6f98bb.png)
![image](https://user-images.githubusercontent.com/82726788/148880651-85368519-0c76-4b5d-a898-71e444a7d266.png)

**Comment by saxoncameron** [comment]
Associated Discord thread:
https://discord.com/channels/752293144917180496/846925957302714388/929933966427963482

@RicBent not sure what's going on here, but other users have still been complaining that automatic card creation hasn't been working again, lately.

**Comment by RicBent** [comment]
Fixed with https://github.com/migaku-official/Migaku-Kanji-Addon/commit/6c3fed5e736d568f9dbe317a9beb4cfda551d405
