### ISSUE TITLE
[BUG] Clicking linked vocab frequently returns irrelevant search results

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/Migaku-Kanji-Addon#156]
An issue I'm coming across fairly frequently now is regarding linked vocab: when clicking a button to display the cards that contain the clicked word, often many of the search results appear unrelated and indeed don't contain the clicked word.

![Pasted_Image_12_1_2022__10_56_am](https://user-images.githubusercontent.com/3240185/149039943-80a55e39-1a8d-4a61-bfb2-5c9df2292dfa.png)

@RicBent let me know how we can nail this down, e.g. if I export some cards for you to be able to reproduce. FWIW I'm coming across this frequently enough that I don't think it'd be hard to find this occurring in your own reviews. Any idea why this might be happening?

**Comment by RicBent** [comment]
Finally fixed with https://github.com/migaku-official/Migaku-Kanji-Addon/commit/d710cf23f5dc828d493203a638061ffe8347d4c6
