### ISSUE TITLE
[BUG] "Lookup" and "Stats" window are completely black.

### ISSUE THREAD

**Issue by Munzu** [migaku-official/Migaku-Kanji-Addon#163]
**Describe the bug**
"Lookup" and "Stats" window are completely black. 

**To Reproduce**
1. Click on "Kanji"  
2. Select "Lookup" or "Stats"
3. Black window will pop up

**Expected behavior**
The correct "Lookup" and "Stats" windows pop up. 

**Desktop (please complete the following information):**
 - OS and Version: Arch Linux, Kernel version 5.17.4-arch1-1, KDE Wayland, Nvidia proprietary drivers
 - Anki Version 2.1.51 (cf78a555)⁩, Python 3.10.4 Qt 6.3.0 PyQt 6.3.0.

**Additional context**
I was using 2.1.49 until now but had to update to 2.1.51 since other plugins broke.

**Screenshots**
![image](https://user-images.githubusercontent.com/31477160/165375387-7115e482-9579-4e16-a699-e6779259f376.png)

**Comment by RicBent** [comment]
Thanks for the report. I will look into that!

**Comment by Munzu** [comment]
I just found out that when I restart Anki, the Stats window works as expected, as long as I don't try to open the Lookup window. Once I try to open the Lookup window, I'll just get black windows for both Stats and Lookup.

To see the Stats window again, I have to restart Anki and open the Stats window without trying to open the Lookup window first.

**Comment by MinmoTech** [comment]
@Munzu 
Is this still an issue with latest Kanji God and Anki versions? :)
