### ISSUE TITLE
[BUG] Can't install other add-ons when Migaku Kanji GOD is enabled

### ISSUE THREAD

**Issue by Munzu** [migaku-official/Migaku-Kanji-Addon#164]
**Describe the bug**
When Migaku Kanji GOD is enabled, I can't install any other add-on. 

After clicking on "Get Add-ons..." and pasting in any add-on code (even those that are explicitly compatible with 2.1.51), Anki says "No updates available". As far as I know, that should only be shown when I press "Check for Updates". When I do press on "Check for Updates", it briefly says "Checking..." and then nothing happens. When I press "Check for Updates" again, nothing happens, not even a message.

This wasn't a problem on 2.1.49. I only just updated to 2.1.51 so I can't say anything about 2.1.50. This happens on Qt5, as well as Qt6.

**To Reproduce**
1. Click on "Tools"
2. Click on "Add-ons"
3. Click on "Get Add-ons"
4. Paste any add-on code
5. Click "OK"
6. Observe "No updates available" message

**Expected behavior**
Anki should try to install the add-on or throw an error if there are problems. "No updates available" should only be shown when I press "Check for Updates". 

**Desktop (please complete the following information):**
 - OS and Version: Arch Linux, Kernel 5.17.5-arch1-1
 - Anki Version 2.1.51, Qt5 and Qt6
 - AUR Package: `anki`, but also happens with `anki-bin` and `anki-qt6`
 - KDE Plasma
 - Wayland
 - Nvidia proprietary drivers

**Additional context**
When I disable Migaku Kanji GOD, I can install add-ons normally.

**Comment by Epicrex** [comment]
Just wanted to add that I haven't seen anyone not with this issue.

**Comment by MinmoTech** [comment]
Current error message:
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-6.3.5-zen1-1-zen-x86_64-with-glibc2.35
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-06-09 19:54:54

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.addons", line 1186, in _download_done
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "aqt.addons", line 1163, in <lambda>
  File "aqt.addons", line 1179, in _download_all
TypeError: download_and_install_addon() got an unexpected keyword argument 'force_enable'
```

**Comment by MinmoTech** [comment]
Fixed in https://github.com/migaku-official/Migaku-Kanji-Addon/commit/aa1c551b6c3e569449f2e10e32995021bc3d310b
