### ISSUE TITLE
[BUG] Installing Addons for Anki not possible

### ISSUE THREAD

**Issue by Sakura1702** [migaku-official/Migaku-Kanji-Addon#167]
Hello Together,

I would like to install the Addon Migaku-Kanji-GOD. If I enter the extension code, Anki let me know that the download was successful. After that I should restart Anki so that the extension could work. When I reopen Anki I always get to 2 Bug-informations:

**First one:**

Fehler
Es ist ein Fehler aufgetreten. Bitte starten Sie Anki neu und halten Sie während des Startvorgangs die Umschalttaste gedrückt, damit Anki die installierten Erweiterungen temporär deaktiviert.
Wenn das Problem nur auftritt, wenn die Erweiterungen aktiviert sind, dann benutzen Sie bitte den Menueintrag Extras > Erweiterungen um die problembehaftete Erweiterung durch selektives Deaktivieren herauszufinden.
Wenn Sie die entsprechende Erweiterung herausgefunden haben, dann bitten wir, dass Sie sich mit einem entsprechenden Problembericht an die Support-Seite für Erweiterungen wenden, damit der Fehler behoben werden kann.
Debuginformationen:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-09-02 13:12:06

Caught exception:
Traceback (most recent call last):
  File "C:\Users\corin\AppData\Roaming\Anki2\addons21\1872210448\text_parser.py", line 120, in run
    self.target()
  File "C:\Users\corin\AppData\Roaming\Anki2\addons21\1872210448\text_parser.py", line 178, in _download
    with zipfile.ZipFile(download_path) as zf:
  File "zipfile", line 1257, in __init__
  File "zipfile", line 1324, in _RealGetContents
zipfile.BadZipFile: File is not a zip file

**second one:**
Fehler
Es ist ein Fehler aufgetreten. Bitte starten Sie Anki neu und halten Sie während des Startvorgangs die Umschalttaste gedrückt, damit Anki die installierten Erweiterungen temporär deaktiviert.
Wenn das Problem nur auftritt, wenn die Erweiterungen aktiviert sind, dann benutzen Sie bitte den Menueintrag Extras > Erweiterungen um die problembehaftete Erweiterung durch selektives Deaktivieren herauszufinden.
Wenn Sie die entsprechende Erweiterung herausgefunden haben, dann bitten wir, dass Sie sich mit einem entsprechenden Problembericht an die Support-Seite für Erweiterungen wenden, damit der Fehler behoben werden kann.
Debuginformationen:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-09-02 13:12:06

Caught exception:
Traceback (most recent call last):
  File "C:\Users\corin\AppData\Roaming\Anki2\addons21\1872210448\text_parser.py", line 129, in finished_download
    aqt.mw.progress.finish()
  File "aqt.progress", line 230, in finish
  File "aqt.progress", line 274, in _closeWin
TypeError: isdeleted() argument 1 must be PyQt6.sip.simplewrapper, not None

**Problem:**
After closing the bug-informations another window opens: Refreshing collections words...
But nothing happens after that. The extension is unfortunatly not working with my Anki Version ⁨2.1.54 (b6a7760c)⁩.

Does anybody have any idea how it would work? I deleted and reinstalled this extensions already at least five times and nothing changed.

Thank you very much!
Sakura

**Comment by MinmoTech** [comment]
Duplicate of https://github.com/migaku-official/Migaku-Kanji-Addon/issues/164

We will work on this soon
