### ISSUE TITLE
[BUG] On the screen for automatically adding Kanji cards after card creation, the Kanji are not colored

### ISSUE THREAD

**Issue by Ei3dlo** [migaku-official/Migaku-Kanji-Addon#185]
**Describe the bug**
When adding a new card with a Kanji that haven't already been added, it causes an error message. This is with the option "Confirm Kanji card that get added automatically". If this option is disabled it causes Anki to crash after adding the new card.

This is the error message: 

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.63 (f356f177) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-6.3.6-100.fc37.x86_64-x86_64-with-glibc2.35
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-06-13 18:38:24
Add-ons possibly involved: ⁨Migaku Kanji GOD⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "/home/user/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1872210448/kanji_confirm_dialog.py", line 221, in <lambda>
    lambda: cls._show_new_kanji(ct_kanji, parent)
  File "/home/user/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1872210448/kanji_confirm_dialog.py", line 212, in _show_new_kanji
    cls.instance = cls(parent, ct_kanji)
  File "/home/user/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1872210448/kanji_confirm_dialog.py", line 146, in __init__
    ct_kmw = KanjiMarkWidget()
  File "/home/user/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1872210448/kanji_confirm_dialog.py", line 82, in __init__
    self.setResizeMode(QListView.Adjust)
  File "aqt.qt.qt5_compat", line 342, in __getattr__
AttributeError: type object 'QListView' has no attribute 'BrowserLayout'

**To Reproduce**
1. Enable "Confirm Kanji card that get added automatically"
2. Click on "Add", then add a card with a unknown Kanji
3. See error

**Expected behavior**
I was following the user tutorial https://youtu.be/y9bmWLvUBQo?t=484 and was expecting the window to add the Kanji and all the primitives to show up.

**Desktop (please complete the following information):**
 - OS and Version: Fedora 37, The same also happens on Fedora 38. 
 - Anki Version ⁨2.1.63 (f356f177)⁩
This is Anki from Flatpak (Flathub repository)
Python 3.9.15 Qt 6.5.0 PyQt 6.5.0

Also using the latest release of Migaku 1.0.1, but the same bug was also in 1.0.0-beta.14 

I haven't tried on Windows 11 yet, but I can try later if necessary.

**Comment by Ei3dlo** [comment]
1.0.2 fixed the error, however I'm not sure if this is correct. There is are no colors around the Kanji. Not sure what is happening.

![bilde](https://github.com/migaku-official/Migaku-Kanji-Addon/assets/17211897/584afc91-70f8-4be7-a67a-6f43619694de)

**Comment by MinmoTech** [comment]
Can confirm the issue.

Add Kanji screen on Anki 2.1.52:
![image](https://github.com/migaku-official/Migaku-Kanji-Addon/assets/25890405/0740a4f1-5c32-4e64-9630-f808b1dbe411)

Add Kanji screen on Anki 2.1.65:
![image](https://github.com/migaku-official/Migaku-Kanji-Addon/assets/25890405/eb842137-6765-434c-8b9e-b1e94decb2ba)


@hgiesel Could you please look into this? :)

**Comment by hgiesel** [comment]
Was closed by #188
