### ISSUE TITLE
[FEATURE] [QUESTION] Retain note type customisations?

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/Migaku-Kanji-Addon#19]
People have expressed frustration that changes they make to the note types in Anki (i.e. customised CSS/HTML) are reset every time they restart Anki. While it's possible to edit the `models/*` files directly in the addon folder, that's not easy or obvious for most users.

I'm guessing the note type is regenerated/restored to keep the Kanji Settings config up-to-date, right? Any way we could do this without completely overwriting the existing templates, to preserve any customisations...?

**Comment by saxoncameron** [comment]
Context: we'll add the warning message dialog (as discussed above) before closing this one.

**Comment by saxoncameron** [comment]
(Oops my bad)

**Comment by RicBent** [comment]
Notice added with cabcec4a6efbfaecaa915e321ecabd3e03e8d0a

https://user-images.githubusercontent.com/12817990/142702536-52141c4f-59f4-494a-9e24-6ac214a986ba.mp4

(Visual glitches caused by recording tool)

**Comment by saxoncameron** [comment]
Typo

<img width="487" alt="Pasted_Image_20_11_21__10_34_am" src="https://user-images.githubusercontent.com/3240185/142704131-972961f0-3565-4361-acf8-c67c0cd105d2.png">

**Comment by RicBent** [comment]
Nice catch. Fixed.
