### ISSUE TITLE
[FEATURE] Distribute furigana for example words

### ISSUE THREAD

**Issue by RicBent** [migaku-official/Migaku-Kanji-Addon#43]
Right now all reading characters are shown as furigana like this:

`<ruby>錆びる<rt>さびる</rt></ruby>`
# <ruby>錆びる<rt>さびる</rt></ruby>

However, only furigana that are necessary should be shown like this:

`<ruby>錆<rt>さ</rt>びる</ruby>`
# <ruby>錆<rt>さ</rt>びる</ruby>

The easiest solution would be using `distributeFurigana` from Yomichan (https://github.com/FooSoft/yomichan/blob/master/ext/js/language/sandbox/japanese-util.js) (GNU GPL).

**Comment by archiif** [comment]
Can this feature be added to the Migaku Japanese Addon too?

**Comment by saxoncameron** [comment]
That's a good question - @RicBent have you already updated the JP addon in your upcoming release?

**Comment by RicBent** [comment]
Yep it is. Including distributed Furigana:

![image](https://user-images.githubusercontent.com/12817990/143084512-c27f5e67-685b-4fc1-b82c-5a93ee73d380.png)
