### ISSUE TITLE
[FEATURE] Drawable canvas for production card front

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/Migaku-Kanji-Addon#53]
Putting a drawable on the front of production card templates would be nice:

This deck has a cool draw-in-place canvas, complete with stroke nice-ifying/correction:
https://ankiweb.net/shared/info/1558868613

![image](https://user-images.githubusercontent.com/3240185/140233461-9e20ec83-12eb-43d6-926a-fbe2250537dc.png)

It might be a nice feature/toggle to offer similar/same stroke nice-ifying/correction (especially since drawing on mobile and touch screens is always a little janky).

It might be a good idea to somehow/somewhere show the same drawn-canvas on the back of the card, so the user can compare the "correct" answer/stroke-order with what they've drawn, but that could be a challenge.

**Comment by saxoncameron** [comment]
Archiving for now - certainly not in demand, as most users practising kanji production are doing it in handwriting. On mobile there is already the scratch pad (at least, on iOS).

A nice to have, and perhaps optional feature in the future.

**Comment by aslucki** [comment]
> It might be a good idea to somehow/somewhere show the same drawn-canvas on the back of the card, so the user can compare the "correct" answer/stroke-order with what they've drawn, but that could be a challenge.

For future reference, this solution can be used for exchanging data between the front and back of the card: https://github.com/SimonLammer/anki-persistence

Canvas context can be converted to base64 string, stored using the code in linked repo and then displayed as an image on the back of the card.

**Comment by saxoncameron** [comment]
Awesome, that sounds useful @aslucki - thanks for chiming in!

**Comment by saxoncameron** [comment]
Cross-posting a Reddit comment to keep references to this feature centralised:

Reddit user `thehershel` posted screenshots of a solution they DIYd for themselves ([thread](https://www.reddit.com/r/LearnJapanese/comments/r9mbyf/comment/hndhp8y/?utm_source=share&utm_medium=web2x&context=3
)):
> I duct-tape added drawing functionality to "production" cards and now it's almost as perfect as I could imagine.
> After some tweaking, I added displaying drew kanji on the card's back.
![image](https://user-images.githubusercontent.com/3240185/144838500-217cc8e7-1de4-48cb-9086-b604e9bcc72b.png)![image](https://user-images.githubusercontent.com/3240185/144838575-ff58636a-9a81-441b-9a03-e932c6da33e3.png)

**Comment by aslucki** [comment]
I'm adding gists with manual, local changes to the card's template to present a possible approach:
Front: https://gist.github.com/aslucki/5f4ef7a55feab1bcc4e5e4fa828a7fd1#file-card_front-html
Back: https://gist.github.com/aslucki/89e7f5790169c56face412aa3d9fef98#file-card_back-html

BTW, Free handwriting can be not just simpler to implement but also superior to that "stroke nice-ifying/correction" (for example stokes auto snapping to correct position) mentioned in the original description of the issue.

**Comment by saxoncameron** [comment]
Awesome, thanks for the valuable contribution. We will point people here for those who express interest in this and are comfortable with DIY-ing a solution.

I agree with you that stroke nice-ifying probably just reinforces sloppy handwriting. A free-drawing canvas is a better solution, and an optimal one would show the stroke order - though not sure how feasible that would be.

**Comment by saxoncameron** [comment]
Note for future reference, the screenshots in the initial description seem to be using Hanzi Writer under the hood:
https://hanziwriter.org/docs.html
