### ISSUE TITLE
[BUG] Adding user data on AnkiDroid breaks card

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/Migaku-Kanji-Addon#81]
From Discord user `kooolm#1408`:
https://discord.com/channels/752293144917180496/846925957302714388/907408471480238160
> Sorry of this was already mentioned. So when I rep my kanji deck on mobile (Pixel 4a if it helps), I used to use User Data field to add custom stories or translations for the keywords I didn't know. After the last update when I type something into that field, the back of the card just becomes blank and it stays this way even after I remove what I typed in the user data field. 

> I did update on desktop and it refreshed the cards after the update. Everything else works just like it should after the update, like stroke order now works on mobile, etc.

![image](https://user-images.githubusercontent.com/3240185/140834155-1e832088-8534-4e6b-8f55-64742e5eea31.png)

Unclear if this is happening on just AnkiDroid or iOS too.

**Comment by saxoncameron** [comment]
Update:

After being able to replicate this issue via the above attachment, we resolved to merely mitigate the issue, since the underlying problem seems to be with AnkiDroid. In the latest release, when adding user data to a card on AnkiDroid, the entire card will no longer break, just the kanji diagram. This is because the SVG breaks, (AFAIK, @RicBent). Users can rectify these semi-broken cards via "Refresh Kanji Cards" on desktop, and syncing.

**Comment by RicBent** [comment]
AnkiDroid's editor seems to parse the stroke diagram SVG and just puts the text contents into the field. So you basically end up with halfway broken XML syntax and 1, 2, 3, ... from the stroke order numbers.

When you save the card it just saves what ever is in the text box to the card, I assume.
